Fix inaccuracies in supporting text of CLI options page (#110)
- only some options can be specified multiple times
- the "shorthand" for multiple values to a single argument doesn't exist

```
cargo run -- --scheme http https -- example.com

Error: Network error

Caused by:
    0: error sending request for url (http://https/)
    1: client error (Connect)
    2: dns error
    3: failed to lookup address information: Name or service not known
```